name: Verify Secrets

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check LeetCode Session
        run: echo "LeetCode Session: ${{ secrets.LEETCODE_SESSION }}"
      - name: Check LeetCode CSRF Token
        run: echo "LeetCode CSRF Token: ${{ secrets.LEETCODE_CSRF_TOKEN }}"
